export enum Role {
  USER = 'user',
  MODEL = 'model',
}

export interface Message {
  id?: string;
  role: Role;
  text: string;
  sources?: { title: string; uri: string }[];
  image?: string;
  agentName?: string;
  type?: 'text' | 'image';
  // Tracks whether the message is currently being generated by the AI
  isLoading?: boolean;
}
